---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app garden-plotter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      plotter:
        annotations:
          reloader.stakater.com/auto: "true"
        type: daemonset
        pod:
          nodeSelector:
            chia-plotter: "yes"
          hostNetwork: true
        containers:
          garden:
            image:
              repository: ghcr.io/krobertson/chia-garden
              tag: dev@sha256:f31558be31d3dac084ef794c8f8080e88a25becfe668fa0364d9862169530605
            args:
              - plotter
              - -p
              - /mnt/plots
            env:
              GARDEN_NATS_URL: "nats://nats:4222"
              GARDEN_PLOTTER_MAX_TRANSFERS: "20"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
    persistence:
      tmp-plots:
        enabled: true
        type: hostPath
        hostPath: /var/mnt/plots
        globalMounts:
          - path: /mnt/plots
