---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter-cisco
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
  values:
    fullnameOverride: *app
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraConfigmapMounts:
      - name: *app
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        configMap: *app
        readOnly: true
        defaultMode: 420
    podAnnotations:
      configmap.reloader.stakater.com/reload: *app
    serviceMonitor:
      enabled: true
      params:
        - name: cisco01
          auth: [public_v2]
          module: [cisco_custom]
          target: 192.168.2.88
      path: /snmp
      scrapeTimeout: 10s
