---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app chia-plot-copy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      harvester:
        annotations:
          reloader.stakater.com/auto: "true"
        type: daemonset
        pod:
          nodeSelector:
            chia-plotter: "yes"
          hostNetwork: true
        containers:
          garden:
            image:
              repository: ghcr.io/krobertson/chia-gigahorse-cudaplotter
              tag: v2.2.1.giga35@sha256:ef18504a8ac15adb081dbc523c90af6a1693ebd741477e823727a6ae99cc77d3
            command:
              [
                "/bin/sh",
                "-c"
              ]
            args:
              - ./chia_plot_copy -d -t 192.168.2.180 -- /mnt/plots/plot-*.plot
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
    persistence:
      tmp-plots:
        enabled: true
        type: hostPath
        hostPath: /var/mnt/plots
        globalMounts:
          - path: /mnt/plots
