---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  # Directories
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  SETUP_DIR: "{{.ROOT_DIR}}/setup"
  PRIVATE_DIR: "{{.ROOT_DIR}}/.private"
  # Files
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/.kubeconfig"

env:
  KUBECONFIG: "{{.KUBECONFIG_FILE}}"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"

includes:
  bootstrap: .taskfiles/bootstrap

tasks:

  default: task --list

  init:
    desc: Initialize configuration files
    cmds:
      - mkdir -p {{.PRIVATE_DIR}}
