---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minecraft-rcon-secret
    template:
      engineVersion: v2
      data:
        RCON_PASSWORD: "{{ .RCON_PASSWORD }}"
  data:
    - secretKey: RCON_PASSWORD
      remoteRef:
        key: minecraft
        property: password
