# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minecraft-test
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.15.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  values:
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: java17
    resources:
      requests:
        cpu: 500m
      limits:
        memory: 8Gi
    securityContext:
      runAsUser: &uid 568
      fsGroup: *uid
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    extraEnv:
      TZ: "${TIMEZONE}"
      ENABLE_AUTOPAUSE: FALSE
    extraVolumes:
      - volumeMounts:
        - name: whitelist-config
          mountPath: /data/whitelist.json
        volumes:
          - name: whitelist-config
            configMap:
              name: minecraft-test-ops
              items:
                - key: whitelist.json
    persistence:
      dataDir:
        enabled: true
    serviceAnnotations:
      io.cilium/lb-ipam-ips: "192.168.2.201"
    minecraftServer:
      eula: true
      version: 1.20.4
      type: SPIGOT
      forceReDownload: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 8192M
      difficulty: normal
      spawnProtection: 0
      maxTickTime: -1
      gameMode: survival
      pvp: false
      onlineMode: false
      motd: "R7N Test"
      viewDistance: 12
      spigetResources:
      - 36618 #Prom Exporter
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: LoadBalancer
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          enabled: false
      - name: map
        containerPort: 8123
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 8123
        ingress:
          ingressClassName: internal
          enabled: true
          hosts:
          - name: &host "minecraft.${SECRET_DOMAIN}"
            path: /
          tls:
          - secretName: *host
            hosts:
            - *host
  valuesFrom:
  - kind: Secret
    name: minecraft-rcon-secret
    valuesKey: RCON_PASSWORD
    targetPath: minecraftServer.rcon.password
