---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: readeck-config-pv
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteOnce"]
  iscsi:
    targetPortal: 192.168.2.181:3260
    iqn: iqn.2005-10.org.freenas.ctl:readeck-config
    lun: 0
    fsType: ext4
