---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app chia-plot-sink
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      harvester:
        annotations:
          reloader.stakater.com/auto: "true"
        type: daemonset
        pod:
          nodeSelector:
            chia-harvester: "yes"
          hostNetwork: true
        initContainers:
          init-config-rename:
            image:
              repository: ghcr.io/onedr0p/alpine
              tag: 3.19.1@sha256:0e3067295cc20dafbd4cf63789ccc71858ad555f3998200ca10b271328c7285e
            command:
              [
                "/bin/sh",
                "-c"
              ]
            args:
              - ln -s /config/base/$NODE_NAME.yaml /config/sink.yaml
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
        containers:
          garden:
            image:
              repository: ghcr.io/krobertson/chia-plot-sink-multi
              tag: dev@sha256:ae664d1800a4d717e25a897ee27ae862a63ead854dbc658d8487be8c19878cb3
            command:
              [ "./chia-plot-sink-multi", "-c", "/config/sink.yaml" ]
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
    persistence:
      chia-plots:
        enabled: true
        type: hostPath
        hostPath: /var/mnt
        globalMounts:
          - path: /mnt
      configdir:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config
      plot-sink-configs:
        enabled: true
        type: configMap
        name: chia-plot-sink-configs
        globalMounts:
          - path: /config/base
