---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app chia-plot-sink
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      harvester:
        annotations:
          reloader.stakater.com/auto: "true"
        type: daemonset
        pod:
          nodeSelector:
            chia-harvester: "yes"
          hostNetwork: true
        containers:
          garden:
            image:
              repository: ghcr.io/krobertson/chia-gigahorse-cudaplotter
              tag: v2.2.1.giga35@sha256:20706bda53fdddf950ed7cc607cdf6e52a1639e450c26561854e27bd050b32a1
            command:
              [
                "/bin/sh",
                "-c"
              ]
            args:
              - find /mnt/chia -type d | xargs ./chia_plot_sink
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
    persistence:
      chia-plots:
        enabled: true
        type: hostPath
        hostPath: /var/mnt
        globalMounts:
          - path: /mnt
