---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats-charts
  namespace: flux-system
spec:
  interval: 2h
  url: https://nats-io.github.io/k8s/helm/charts/
