---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app gh-recompute-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      server:
        annotations:
          reloader.stakater.com/auto: "true"
        type: daemonset
        pod:
          runtimeClassName: nvidia
          nodeSelector:
            chia-compute: "yes"
        containers:
          server:
            image:
              repository: ghcr.io/madmax43v3r/chia-recompute
              tag: latest-nvidia@sha256:e021ee5afc8f74ce617dd64a37e52d6412241b87bd3a4aa43a3cb70926f88bc6
            args:
              - ./chia_recompute_server
              - -u
              - gh-recompute-proxy
            env:
              NVIDIA_VISIBLE_DEVICES: "all"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
