
---
ingress:
  - hostname: r7n.dev
    originRequest:
      originServerName: r7n.dev
    service: https://envoy-external.network.svc.cluster.local:443
  - hostname: "*.r7n.dev"
    originRequest:
      originServerName: external.r7n.dev
    service: https://envoy-external.network.svc.cluster.local:443
  - service: http_status:404
