---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-secret # rook-ceph expects this name
    template:
      engineVersion: v2
      data:
        s3-bucket: thanos
        s3-region: us-west-1
        s3-endpoint: "{{ .endpoint }}"
        access-key: "{{ .access_key }}"
        secret-key: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: onepassword-connect
          kind: ClusterSecretStore
      remoteRef:
        key: thanos-secret
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: onepassword-connect
          kind: ClusterSecretStore
      remoteRef:
        key: thanos-secret
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: onepassword-connect
          kind: ClusterSecretStore
      remoteRef:
        key: thanos-secret
        property: endpoint
