---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app partsetup
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      harvester:
        annotations:
          reloader.stakater.com/auto: "true"
        type: daemonset
        pod:
          nodeSelector:
            partsetup: "yes"
          hostNetwork: true
        containers:
          garden:
            image:
              repository: ghcr.io/krobertson/partsetup
              tag: 2024.04.07@sha256:16c0609892fae44d7d96a0bda0448d34de08f8ed547a6ed573775a2b923b80e3
            command:
              [
                "/bin/sh",
                "-c"
              ]
            args:
              - ./partsetup.py && sleep infinity
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            securityContext:
              privileged: true
    persistence:
      disk-mapping:
        enabled: true
        type: configMap
        name: disk-mapping
        globalMounts:
          - path: /config
      host-dev:
        enabled: true
        type: hostPath
        hostPath: /dev
        globalMounts:
          - path: /dev
      host-mnt:
        enabled: true
        type: hostPath
        hostPath: /var/mnt
        globalMounts:
          - path: /mnt
            mountPropagation: Bidirectional
