---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app nvidia-smi
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      harvester:
        annotations:
          reloader.stakater.com/auto: "true"
        type: daemonset
        pod:
          runtimeClassName: nvidia
          nodeSelector:
            nvidia.feature.node.kubernetes.io/gpu: "true"
        containers:
          garden:
            image:
              repository: ghcr.io/krobertson/nvidia-gpu-exporter
              tag: 1.2@sha256:5bc082d019c2398889dc75657e085f001bdbcae9ca9895adca83e8f737f7e781
            command:
              [
                "/bin/sh",
                "-c"
              ]
            args:
              - /setpowerlimit.sh /config/$NODE_NAME.yaml && nvidia-smi && sleep infinity
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            securityContext:
              privileged: true
    persistence:
      nvidia-power-limits:
        enabled: true
        type: configMap
        name: nvidia-power-limits
        globalMounts:
          - path: /config
