---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cuda-plotter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cuda-plotter-secret
    template:
      engineVersion: v2
      data:
        FARMER_ID: "{{ .FARMER_ID }}"
        POOL_LAUNCH_ID: "{{ .POOL_LAUNCH_ID }}"
  dataFrom:
    - extract:
        key: cuda-plotter
