---
auths:
  tripplite_v2:
    community: tripplite
    version: 2

modules:
  tripplite_pdu:
    retries: 5
    timeout: 60s
    walk:
    - 1.3.6.1.4.1.850.1.1.3.2.3.3.1.1.9
    metrics:
    - name: tlpPduOutletActivePower
      oid: 1.3.6.1.4.1.850.1.1.3.2.3.3.1.1.9
      type: gauge
      help: The output active power of a given outlet - 1.3.6.1.4.1.850.1.1.3.2.3.3.1.1.9
      indexes:
      - labelname: tlpDeviceIndex
        type: gauge
      - labelname: tlpPduOutletIndex
        type: gauge
