---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        HASS_DARKSKY_API_KEY: "{{ .HASS_DARKSKY_API_KEY }}"
        HASS_WOEID: "{{ .HASS_WOEID }}"
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HAAS_PUSHBULLET_APIKEY: "{{ .HAAS_PUSHBULLET_APIKEY }}"
  dataFrom:
    - extract:
        key: home-assistant
