---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.7.4@sha256:3db687091769f145839c0a690143c1a63dbb646fd69711684103b575f070b598
            env:
              TZ: America/Los_Angeles
              HASS_HTTP_TRUSTED_PROXY_1: 192.168.2.0/24
              HASS_HTTP_TRUSTED_PROXY_2: 10.69.0.0/16
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes: &probes
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.91.1
            env:
              TZ: America/Los_Angeles
            args: [
              "--auth", "none",
              "--user-data-dir", "/config/.vscode",
              "--extensions-dir", "/config/.vscode",
              "--port", "80",
              "/config"
            ]
            probes: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        ports:
          http:
            port: 8123
          code:
            port: 80
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host hass.r7n.dev
            paths:
              - path: /
                service:
                  port: 8123
        tls:
          - hosts:
              - *host
      code:
        enabled: true
        className: internal
        hosts:
          - host: &host hass-code.r7n.dev
            paths:
              - path: /
                service:
                  port: 80
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: ceph-block
        size: 10Gi
      tmp:
        type: emptyDir
