---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chia-wallet
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: chia-secret
    template:
      engineVersion: v2
      data:
        nemonic.key: "{{ .nemonic }}"
        keyring.yaml: "{{ .keyring_data }}"
        keyring.yaml.lock: ""
  dataFrom:
    - extract:
        key: chia
