---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app chia-farmer
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      chia:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-wallet:
            image:
              repository: ghcr.io/madmax43v3r/chia-gigahorse
              tag: 2.2.1.giga35@sha256:05f52381283856d6538f54804bfea20250acceea2f54221465b7c159a521ee32
            command:
              [
                "/bin/sh",
                "-c"
              ]
            args:
              - mkdir /root/.chia_keys && chmod 700 /root/.chia_keys &&
                ./chia.bin keys add -f /config/keys/nemonic.key -l ""
        containers:
          app:
            image:
              repository: ghcr.io/madmax43v3r/chia-gigahorse
              tag: 2.2.1.giga35@sha256:05f52381283856d6538f54804bfea20250acceea2f54221465b7c159a521ee32
            env:
              CHIA_SERVICES: "node farmer-only wallet"
              CHIA_UPNP: "false"
              CHIAPOS_MAX_GPU_DEVICES: "0"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
          exporter:
            image:
              repository: ghcr.io/chia-network/chia-exporter
              tag: main@sha256:740691b42ccea25174bc8ab6752efd10721a66ddace4d06e32361c458e237d70
            ports:
              - name: metrics
                containerPort: 9914
                protocol: TCP
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
    service:
      app:
        controller: chia
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.2.204
        ports:
          sync:
            port: 8444
          rpc:
            port: 8555
          farm:
            port: 8447
    persistence:
      datadir:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /root
      blockchain:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 320Gi
        globalMounts:
          - path: /root/.chia/mainnet
      wallet:
        enabled: true
        type: secret
        name: chia-wallet-secret
        globalMounts:
          - path: /config/keys
