---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: chia-farmer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chia-farmer
  podMetricsEndpoints:
  - port: metrics
