---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-create
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: minecraft
  values:
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    image:
      repository: itzg/minecraft-server
      tag: 2026.2.1-java21@sha256:115f666dac309116d0921549a935f02c2f8e9114282590ad77423ac357319992
    resources:
      limits:
        memory: 8Gi
      requests:
        cpu: 1000m
        memory: 4Gi
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    extraEnv:
      TZ: "America/Los_Angeles"
      INIT_MEMORY: 25%
      MAX_MEMORY: 90%
      MODPACK_PLATFORM: MODRINTH
      MODRINTH_MODPACK: https://modrinth.com/modpack/jonklscreatemodpack/version/3.1.1
    persistence:
      storageClass: iscsi-retain
      dataDir:
        enabled: true
        # WTF: its Size and not size
        Size: 20Gi
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: mc-create.r7n.dev
      gatus.home-operations.com/endpoint: |-
        group: services
    minecraftServer:
      eula: true
      version: 1.20.1
      type: FABRIC
      whitelist: Zerimis
      ops: Zerimis
      pvp: false
      onlineMode: true
      difficulty: easy
      gameMode: survival
      levelType: largebiomes
      viewDistance: 12
      motd: "R7N Create"
      spigetResources:
      - 100301 # bigger barrels
      - 60383  # angelchest
      downloadModpackUrl: "https://cdn.modrinth.com/data/HqonU57y/versions/rlTgMYB4/Create%2B%203.1.1.mrpack"
      modrinth:
        downloadDependencies: required
        projects:
          - patchouli
          #- jonklscreatemodpack
          #- create-tfmg
          - create-let-the-adventure-begin
          - create-transmission!:1.0.4+fabric-create6-1.20.1
          - createaddition:1.2.6
          - slice-and-dice
      modUrls:
        - https://github.com/cpburnz/minecraft-prometheus-exporter/releases/download/1.20.1-fabric-1.2.1/Prometheus-Exporter-1.20.1-fabric-1.2.1.jar
      rcon:
        enabled: true
      extraPorts:
        - name: metrics
          containerPort: 19565
          service:
            enabled: true
            port: 19565
    #mcbackup:
    #  enabled: true
    #  resticHostname: minecraft-survival
    #  backupMethod: restic
    #  backupInterval: 1h
    #  pauseIfNoPlayers: "true"
    #  pruneResticRetention: "--keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75"
    #  envFrom:
    #    - secretRef:
    #      name: spaceengineers
