---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-secret
    template:
      data:
        # App
        username: "{{ .FORGEJO_ADMIN }}"
        email: "{{ .FORGEJO_ADMIN_EMAIL }}"
        password: "{{ .FORGEJO_ADMIN_PASSWORD }}"
        FORGEJO_SECRET_KEY: "{{ .FORGEJO_SECRET_KEY }}"
        FORGEJO_INTERNAL_TOKEN: "{{ .FORGEJO_INTERNAL_TOKEN }}"
        REDIS_URL: |-
          redis://dragonfly.storage.svc.cluster.local:6379/2
        # S3
        FORGEJO_AWS_ACCESS_KEY_ID: "{{ .FORGEJO_AWS_ACCESS_KEY_ID }}"
        FORGEJO_AWS_SECRET_ACCESS_KEY: "{{ .FORGEJO_AWS_SECRET_ACCESS_KEY }}"
        # OIDC
        key: "{{ .OAUTH_CLIENT_ID }}"
        secret: "{{ .OAUTH_CLIENT_SECRET }}"
        # Database
        POSTGRES_USERNAME: &dbuser "{{ .FORGEJO_POSTGRESQL__USER }}"
        POSTGRES_PASSWORD: &dbpass "{{ .FORGEJO_POSTGRESQL__PASSWORD }}"
        POSTGRES_DB: &dbname "forgejo"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: "postgres.storage.svc.cluster.local"
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: forgejo
