---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Git:
      - kubesearch:
        - icon: kubernetes-dashboard.png
          href: 'https://kubesearch.dev/'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Calendar:
        - Agenda:
            widget:
              type: calendar
              view: agenda # optional - possible values monthly, agenda
              maxEvents: 20 # optional - defaults to 10
              integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Sonarr # service name for that widget
                - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Radarr # service name for that widget
    - Infrastructure:
      - Home Assistant:
          icon: home-assistant.svg
          href: http://192.168.1.221:8123/
      - Unifi:
          href: https://unifi.ui.com
          icon: unifi.png
          description: Unifi Dashboard
          widget:
            type: unifi
            url: https://192.168.1.1:443
            username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
            password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
  settings.yaml: |
    title: R7N Homepage

    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100

    theme: dark
    #color: slate
    useEqualHeights: true
    layout:
      Calendar:
        style: column
        icon: mdi-calendar
      Infrastructure:
        header: true
        style: row
        columns: 5
  widgets.yaml: |
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - resources:
        cpu: true
        memory: true
        disk: /
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
