---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .HOMEPAGE_UNIFI_USER }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .HOMEPAGE_UNIFI_PASS }}"
       ## Downloads
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
  data:
    - secretKey: HOMEPAGE_UNIFI_USERNAME
      sourceRef:
        storeRef:
          name: onepassword-connect
          kind: ClusterSecretStore
      remoteRef:
        key: *name
        property: password
    - secretKey: HOMEPAGE_UNIFI_PASSWORD
      sourceRef:
        storeRef:
          name: onepassword-connect
          kind: ClusterSecretStore
      remoteRef:
        key: *name
        property: password
