---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nvidia-gpu-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-gpu-exporter
  podMetricsEndpoints:
  - port: metrics
