---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chia-ca
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: chia-ca-secret
    template:
      engineVersion: v2
      data:
        chia_ca.crt: "{{ .chia_ca_cert }}"
        chia_ca.key: "{{ .chia_ca_key }}"
        private_ca.crt: "{{ .private_ca_cert }}"
        private_ca.key: "{{ .private_ca_key }}"
  dataFrom:
    - extract:
        key: chia
