---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app chia-harvester
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      harvester:
        annotations:
          reloader.stakater.com/auto: "true"
        type: daemonset
        pod:
          nodeSelector:
            chia-harvester: "yes"
        initContainers:
          init-plots:
            image:
              repository: ghcr.io/madmax43v3r/chia-gigahorse
              tag: 2.3.0.giga36@sha256:1494354065a02dc80bf35611be10e4702f72e58b3fe0942747735f1f8fce0dea
            command:
              [
                "/bin/sh",
                "-c"
              ]
            args:
              - ./chia.bin init --fix-ssl-permissions ;
                for d in /mnt/plots/*/ ; do ./chia.bin plots add -d "$d" || continue ; done
        containers:
          app:
            image:
              repository: ghcr.io/madmax43v3r/chia-gigahorse
              tag: 2.3.0.giga36@sha256:1494354065a02dc80bf35611be10e4702f72e58b3fe0942747735f1f8fce0dea
            env:
              CHIA_SERVICES: "harvester"
              CHIA_UPNP: "false"
              CHIA_CA: "/config/chia-ca"
              CHIA_FARMER_ADDRESS: "chia-farmer.chia.svc.cluster.local"
              CHIA_FARMER_PORT: "8447"
              CHIAPOS_MAX_GPU_DEVICES: "0"
              CHIAPOS_RECOMPUTE_HOST: "gh-recompute-proxy:11988"
              CHIA_LOG_LEVEL: "DEBUG"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
    persistence:
      datadir:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /root
      chia-plots:
        enabled: true
        type: hostPath
        hostPath: /var/mnt/chia
        globalMounts:
          - path: /mnt/plots
      chia-ca:
        enabled: true
        type: secret
        name: chia-ca-secret
        globalMounts:
          - path: /config/chia-ca
